/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author gusta
 */
public class TelaMenuArtista extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenuArtista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BMAVoltar = new javax.swing.JButton();
        BCAlbum = new javax.swing.JButton();
        BEMusica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("MENU ARTISTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 360, 60));

        BMAVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BMAVoltar.setText("VOLTAR");
        BMAVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMAVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(BMAVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 160, -1));

        BCAlbum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BCAlbum.setText("CRIAR ALBUM");
        BCAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCAlbumActionPerformed(evt);
            }
        });
        jPanel1.add(BCAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 310, -1));

        BEMusica.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BEMusica.setText("ENVIAR MUSICA");
        BEMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEMusicaActionPerformed(evt);
            }
        });
        jPanel1.add(BEMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BMAVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMAVoltarActionPerformed
        // TODO add your handling code here:
        
        TelaMenu tMenu = new TelaMenu();
        tMenu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BMAVoltarActionPerformed

    private void BCAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCAlbumActionPerformed
        TelaCadastroAlbum tAlbum = new TelaCadastroAlbum();
        tAlbum.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_BCAlbumActionPerformed

    private void BEMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEMusicaActionPerformed

        // TODO add your handling code here:
        TelaCadastroMusica tCMusica = new TelaCadastroMusica();
        tCMusica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BEMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuArtista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCAlbum;
    private javax.swing.JButton BEMusica;
    private javax.swing.JButton BMAVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
